# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{businessPlanR}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab businessPlanR\cr
#' Type: \tab Package\cr
#' Version: \tab 0.1-0\cr
#' Date: \tab 2023-08-14\cr
#' Depends: \tab R (>= 4.0.0)\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://www.c3s.cc\cr
#' }
#'
#' @title
#' \packageTitle{businessPlanR}
#' @author
#' \packageAuthor{businessPlanR}
#'
#' Maintainer: \packageMaintainer{businessPlanR}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL